### ISSUE TITLE
nodes are installed with k3s but I do not see images/service yet

### ISSUE THREAD

**Issue by walidshaari** [DavidZisky/60sk3s#11]
the nodes master and worker are endlessly loopings waiting for API server to be accessible 
- from the nodes I can curl to the API master, need to troubleshoot more

**Comment by DavidZisky** [comment]
What cloud are you using?

**Comment by walidshaari** [comment]
GCP. will revisit it when I have some free time, hopefully within the next couple of days. before first I am trying to get more acquainted with k3s

**Comment by walidshaari** [comment]
any reason why not use https://github.com/alexellis/k3sup, I do not have any opinion regarding it, to use or not, just asking?

**Comment by DavidZisky** [comment]
@walidshaari I didn't use GCP version for a while so maybe indeed it needs some refresh. Thanks for pointing out, I will check out as well.

About the k3sup - the main difference is that k3sup doesn't provision machines for you.

**Comment by DavidZisky** [comment]
Just tested GCP version and it works fine so it must be something related to your setup. If you'll need any help with debugging feel free to post some logs
