### ISSUE TITLE
Can't read logs from the cluster

### ISSUE THREAD

**Issue by VladyslavLukyanenko** [DavidZisky/60sk3s#13]
Failed to load logs: Get "https://10.133.0.7:10250/containerLogs/kube-system/cert-manager-controller-6b4bc9d996-9psds/cert-manager?tailLines=502&timestamps=true": x509: certificate is valid for 127.0.0.1, 188.166.26.113, 188.166.26.113, not 10.133.0.7
Reason: undefined (500)

**Comment by DavidZisky** [comment]
Thanks for opening the issue. Yes, I faced a similar issue recently. Already working on it, fix will come soon.

**Comment by DavidZisky** [comment]
Hey @VladyslavLukyanenko, I finally managed to find some time and fix that. I needed to add internal nodes IP to the deploy script. I was only passing public IP when deploying k3s, so only public IPs were added to k8s cert, but nodes communicate via internal IP, so these need to be specified as well to have them as well trusted.

Fix already committed. Thanks for raising this. Best regards
